name: Feature request
description: Suggest something the game should do
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like
      description: Describe the feature as you'd want to use it.
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why
      description: >
        What would this help you do?
    validations:
      required: true
